### ISSUE TITLE
mypc 기능의 부품 찾기 페이지 구현

### ISSUE THREAD

**Issue by cocorini** [HARl803/mypc-service#4]
## Description
- 유저는 부품 찾기 페이지를 통해 '체크박스'로 필터링 하여 부품을 찾을 수 있다.
- 같은 종류의 부품끼리는 스펙 비교가 가능하다.
- 내가 커스텀 할 PC의 부품을 수정할 수 있다.
- 내가 커스텀 할 PC를 등록할 수 있다.

## Todo
- [x] `/api/v1/parts` 에 매핑되는 controller를 구현합니다.
   - [x] 유저는 부품 조회를 할 수 있습니다.
- [x] 메인 로직을 담은 `service`를 작성합니다.
- [x] FE와 parts에 대한 정보를 담는 Dto의 속성 값들을 정확하게 상의해 결정합니다.
   - [x] dto 구조 모두 변경
   - [x] dto 구조 변경에 따른 서비스 로직 변경
